name: pep8

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: installing system dependencies
      run: sudo apt-get install -y python3 python3-pip
    - name: installing flake8 linter
      run: sudo pip3 install flake8
    - name: running linter on python files
      run: flake8 scripts/
