name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: printing rust version
      run: rustc --version
    - name: printing cargo version
      run: cargo --version
    - name: building the project
      run: cargo build
    - name: testing the project
      run: cargo test
